Add await
googleapis/nodejs-bigtable pull request #1217
Opened 2023-01-26 15:56 UTC by danieljbruce

This should fix a flakey test issue where we wait for an instance to be created.

2023-01-26 19:53 UTC, kolea2 requested changes, later dismissed
please prefix this with "test" rather than "fix" so it does not show up in the release notes as a bugfix

2023-01-26 20:22 UTC, danieljbruce commented
> please prefix this with "test" rather than "fix" so it does not show up in the release notes as a bugfix

Done!

2023-01-27 17:16 UTC, bcoe commented on samples/test/filters.js
> +createTestInstance();
This will create an `unhandledRejection`, so I think we shouldn't do this in the top level.

2023-01-27 20:27 UTC, danieljbruce commented
Closed in favour of moving `obtainTestInstance` instead.

2023-01-27 20:27 UTC, closed without merging