refactor: Pull readModifyWriteRow request building into a single module so that it can live alongside its inverse function
googleapis/nodejs-bigtable pull request #1529
Opened 2024-11-29 19:55 UTC by danieljbruce

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/nodejs-bigtable/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

2024-11-29 20:40 UTC, danieljbruce commented on src/row-data-utils.ts
>      });
All the code removed in this file now lives in getRMWRRequest and one call to getRMWRRequest will be made to build the request.

2024-12-02 19:26 UTC, daniel-sanche requested changes
Do you think you can move this gapic<->veneer translation code into the test proxy codebase? I have concerns that this change adds more layers of abstraction, complexity, and room for bugs to the library, just to support tests

But my larger concern is that IMO the test proxy should only interact with the library's public API, never share internal helpers. Otherwise we run the risk that bugs slip through, because both the library and the test proxy are using the same faulty implementation. There should be a clear wall between the library and the tests

I think the test proxy's role should be:
1. receive gapic request from test runner
2. convert into hand-written representation for interacting with the library
3. execute the rpc on the library
4. convert the results back to a gapic representation
5. send results to test runner

But let me know if you think I'm missing something

2024-12-02 22:21 UTC, danieljbruce commented
> Do you think you can move this gapic<->veneer translation code into the test proxy codebase? I have concerns that this change adds more layers of abstraction, complexity, and room for bugs to the library, just to support tests
> 
> But my larger concern is that IMO the test proxy should only interact with the library's public API, never share internal helpers. Otherwise we run the risk that bugs slip through, because both the library and the test proxy are using the same faulty implementation. There should be a clear wall between the library and the tests
> 
> I think the test proxy's role should be:
> 
> 1. receive gapic request from test runner
> 2. convert into hand-written representation for interacting with the library
> 3. execute the rpc on the library
> 4. convert the results back to a gapic representation
> 5. send results to test runner
> 
> But let me know if you think I'm missing something

I think (1), (2) and (3) are correct if by 3 you mean call the handwritten method in the client library (createRules in this case). 4 and 5 are irrelevant for this PR since this PR only touches request code.

I definitely have no objections to moving `getRMWRRequestInverse` into the test proxy folder since it's only being used by the test proxy anyway. I can undo all the changes to `src/row-data-utils.ts` if you like, I realize it's less risky to make no changes to the `src` folder, but I also think it's more modular if the request construction is a separate function. I think there's a broader discussion about code style on that topic.

2024-12-03 22:18 UTC, daniel-sanche approved these changes

2024-12-03 22:19 UTC, daniel-sanche commented
>  I can undo all the changes to `src/row-data-utils.ts` if you like, I realize it's less risky to make no changes to the `src` folder, but I also think it's more modular if the request construction is a separate function. I think there's a broader discussion about code style on that topic.

I don't have context on the other changes in `src/row-data-utils.ts`, but in general I don't think we want to be sharing internal code between the test proxy and the library if at all possible

2024-12-05 16:45 UTC, merged