chore: drop `paginator` and use gapic to return streams for paginated calls instead
googleapis/nodejs-bigtable pull request #762
Opened 2020-07-13 17:43 UTC by AVaksman

- [] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

2020-07-16 15:25 UTC, stephenplusplus commented
@AVaksman I know it's still a draft, so sorry if I'm jumping in too soon. But, I was wondering if you could describe the intentions behind this when you get the chance? Thanks!

2020-07-16 17:28 UTC, AVaksman commented
gapic now supports paginated calls and its streamified versions directly.

2020-07-16 17:50 UTC, stephenplusplus commented
Does it also retry requests?

2020-07-16 20:10 UTC, AVaksman commented
Yes, gax supports retries for paged calls.
`RetryOptions{retryCodes; backoffSettings;}` can be passed via `gaxOptions.retry` argument.
Streamified version of paged call is essentially same paged call where results pushed one by one via an object mode stream.

2020-07-17 15:57 UTC, stephenplusplus requested changes

2020-07-17 19:22 UTC, AVaksman commented on src/index.ts
> +    const streamified = {listTablesStream: true};
Done

2020-07-17 19:22 UTC, AVaksman commented on src/index.ts
> +    function makeRequestStreamified() {
Done

2020-07-17 19:23 UTC, AVaksman commented on src/instance.ts
> +    const transform = function (
Done!
Have to pass tableId only thought, Table constructor checks for the proper projectId presence.

2020-07-20 13:48 UTC, stephenplusplus approved these changes

2020-07-20 13:48 UTC, stephenplusplus commented
Thanks!

2020-07-27 15:29 UTC, AVaksman commented
@stephenplusplus I added another [unit test](https://github.com/googleapis/nodejs-bigtable/pull/762/commits/e9839fdfc8cfd9eaf12aaa343701215400c9af04) after the approval

2020-07-27 15:34 UTC, stephenplusplus commented
Nice, lgtm!

2020-07-27 18:04 UTC, merged